### ISSUE TITLE
[Bug?]: Confirm Dialog button spacing missing in JS

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/pando#1003]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

There is no spacing between buttons when using the JS API
![image](https://user-images.githubusercontent.com/1745718/213543606-b5bc6b7f-2e87-4631-92bb-03b52d9489ca.png)

### Expected behavior 🤔

Should be space between the buttons.

Due to descendant selector not carrying over in the JS environment
`.confirmDialogBtnGroup button:first-of-type`

### Steps to reproduce 🕹

https://codesandbox.io/s/sc-xkq3xi?file=/src/App.tsx

**Comment by caseybaggz** [comment]
This is a good example for needing a class merge feature since it's technically not adding the classes we are using on the buttons, but only working in the CSS API from the declaration mentioned above.
