### ISSUE TITLE
[Feature?]: allow useTheme to extend preferredTheme

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1014]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are officially a multi-theme (more than 2) product, so we need to update the `useTheme` hook to extend the common `light | dark` with whatever the users want to add.

[See Type parameters docs](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#type-parameters)

### Examples 🌈

API should work something like this:

```typescript
type FlowTypes = 'flow-dark' | 'flow-light'

const { theme, toggleTheme } = useTheme<FlowTypes>()
```

**Comment by nicholasmackey** [comment]
✋ I can take on this one as well.

**Comment by caseybaggz** [comment]
@nicholasmackey go ahead and also replace the code in the HS dev sandbox with your hook (use a relative path the to `react-utils` folder!

**Comment by caseybaggz** [comment]
@nicholasmackey let's also update the `localStorage` key to now use `pandoTheme`.

**Comment by nicholasmackey** [comment]
> @nicholasmackey let's also update the `localStorage` key to now use `pandoTheme`.

Sounds good. So to clarify instead of:
`const THEME_KEY = 'data-theme'`
you'd like it to be:
`const THEME_KEY = 'pandoTheme'`?

**Comment by caseybaggz** [comment]
@nicholasmackey almost. The html tag should still use 'data-theme' but only the localStroage key should use "pandoTheme"

**Comment by caseybaggz** [comment]
@nicholasmackey so, specifically, there will now be 2 keys: `HTML_ATTR` and `LOCAL_STORAGE_KEY`:

```javascript
const HTML_ATTR= 'data-theme'
const LOCAL_STORAGE_KEY = 'pandoTheme'
```
