### ISSUE TITLE
[Docs?]: add useTheme API

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1015]
### Latest version

- [X] I have checked the latest version

### Summary 💡

Need to create a page in the development/react-utils section for the new useTheme hook.

**Comment by nicholasmackey** [comment]
I can take this one on. 
Do any sandboxes need to be created for this or can it just follow the same pattern as the other hook docs?

**Comment by caseybaggz** [comment]
> I can take this one on. Do any sandboxes need to be created for this or can it just follow the same pattern as the other hook docs?

You can just copy/paste/update one of the other hook API pages. I'll update the README.md to be more valuable for contributors to the docs site (i.e. don't follow what is currently on there).

**Comment by caseybaggz** [comment]
@nicholasmackey see #1021
