### ISSUE TITLE
[Feature?]: Support placeholder option item

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/pando#1030]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The `getSelectOptionProps` currently doesn't support props for an initial placeholder option in a list (i.e. first item that says "Choose item", etc.). The API should work in an intuitive way that will return the props if a user provides a `options.placeholder` value.

This will return the following props to be applied to an `option` element

```typescript
interface placeholderOptionProps {
  hidden: true,
  disabled: true,
  value: ''
}
```

If the `options.placeholder` value is empty, the helper should return the normal props expected for an option that is selectable in the list.

### Examples 🌈

```jsx
const { label as placeholderLabel, ...placeholderProps } = getSelectOptionProps({ placeholder: 'Choose option' })

<select>
  <option {...placeholderProps}>{placeholderLabel}</option>
  <option {...getSelectOptionProps({ value: "1" })}>Option 1</option>
  <option {...getSelectOptionProps({ value: "2" })}>Option 2</option>
</select>
```

Based on this example, if the API is not accepting a `label` option, it should to make the returning props/API more fluid (and match our other APIs).

### Motivation 🔦

Headless Styles, SelectOptions API

**Comment by caseybaggz** [comment]
@Rykus0 I don't think we need a `kind` prop. If there's no `value` given, just return placeholder props. Make sense?

**Comment by Rykus0** [comment]
@caseybaggz it does, but if we do that people won't be able to use an empty string for a value.  These props make is so once another option is selected, the placeholder can't be chosen again.  It's not too hard to work around, but I didn't think we wanted to impose that kind of limitation based on the value alone.

**Comment by caseybaggz** [comment]
> 

I thought in Select, you are required to have an option chosen at all times unless it is the first time ever being used? I would rather add it and know we need it more flexible than make an API that is naturally less intuitive to begin with if that makes sense?

**Comment by Rykus0** [comment]
If no selection is specified, it defaults to the first in the list.  Something is always selected, and it's often requested to have it start "blank", though there are debates around that, similar to radio buttons.

But this particular setup was to make it so that the "placeholder" option is not selectable.  So it could only be displayed by default (system-set value), but once a valid choice is made, it's not available anymore.  

I added it as a note because some people had asked about the placeholder, and I saw it being used a lot as more of a secondary label than a blank choice. I was trying to provide an approach for required selects, similar to radio buttons.

I think it would be better to remove this and that tip from the docs, and encourage a regular, blank option if a non-response is allowed, and using the field message for additional labeling or information.  Having a default option that is labeled something like "choose one" is redundant anyway and can be confusing.

**Comment by caseybaggz** [comment]
@Rykus0 all good points here. I would say, then that we could do the same intuitive behavior based on the placeholder optional key then and not the value (to allow the blank option you mentioned). So, if someone provides a placeholder key, then it only returns the placeholder stuff. If no placeholder value given, it returns the normal stuff.

Thoughts on that approach?

**Comment by Rykus0** [comment]
@caseybaggz Yeah, good idea, that feels better to me.
