### ISSUE TITLE
[Bug?]: CSS Module generation creates empty property when using psuedo-classes

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1038]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If we use any type of psuedo-class that's not directly tied to another class (i.e. `:is`), the code generation just defaults to an empty property which makes it buggy to use as an Object.

### Expected behavior 🤔

Should probably have a list of specific psuedo-classes that we just use it's name for the property generation. For example, `:is` would use `'is'` as the property name.

### Steps to reproduce 🕹

Steps:

1. Open up HS sandbox
2. Add a `:is()` selector to the buttonCSS.module.css file
3. Check out the generated result

### Context 🔦

Headless Styles, sandbox, Vite plugin

**Comment by Rykus0** [comment]
Should we preserve the pseudo-class instead of replacing?  Most of them can be on their own.  Or is it easier to drop the colon?  I have a branch ready that preserves the name, but it's easily changed.

**Comment by caseybaggz** [comment]
@Rykus0 we shouldn't change anything it is already doing *except* ensuring a missing property just uses the psuedo class name without the colon. Outside of that specific thing, it is working how we want for this topic.

**Comment by Rykus0** [comment]
There are 2 cases currently that would be affected, and I want to make sure I'm understanding correctly.

First case is `:root`, which would become `root` in the JS file (`styles.root`).
Second case is `::placeholder`, which would become `placeholder` in the JS file (`styles.placeholder`).

If we take that approach, we just have to be a bit more careful by avoiding classes with the same name (`.placeholder`), or adding a selector before the pseudo-class (`*` if applying everywhere, like the placeholder) either in the CSS or programmatically where appropriate.  

I don't think this would be a problem; `root` should be fine, and the placeholder can be adjusted.  I just want to make sure I'm thinking it through and understanding the solution.

**Comment by caseybaggz** [comment]
@Rykus0 no I don't think there is a misinterpretation on the bugfix request. We are not creating new classes because it's a JS Object, it is just creating a property name to be used in the JS generated styles.

This:
```css
:is(.something) {}
```

Is currently generated to this:
```javascript
{
  '': {
   something: {..}
  }
}
```

Instead, we need it to generate **specific** pseudo classes (`:root`, `:is`, `:has`, etc.) to this:
```javascript
{
 root: {...}
 is: {
  something: {...}
 }
 has: {...}
}
```

Does that make sense?

**Comment by caseybaggz** [comment]
I would use this list as a guide:
https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by caseybaggz** [comment]
@Rykus0 never mind, ignore everything I just said. It was indeed I that was miss-interpreting you! 🙈 Yeah, I don't see that as a big deal at all. We literally shouldn't be doing that in general as it's a pretty bad pattern to use in our project and doesn't even follow the current design we have.

**Comment by Rykus0** [comment]
Ok, cool, that's what I was thinking, too.  And I can refactor the one place where we have the `::placeholder` so it's attached to the input selector, rather than being on its own.  I'll have this ready to review shortly
