### ISSUE TITLE
[Feature?]: Add "CAP" product icons

### ISSUE THREAD

**Issue by taitems** [pluralsight/pando#1096]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm unaware of the historical significance or taxonomy of "CAP", but I have taken over a Skills design that uses the CAP grouping of category specific icons that represent `security`, `machine learning` etc.

Some of these icons exist in Pando, such as `WindowsIcon`, but not all. I'm assuming these were included as they are generic enough but perhaps ML is too Skills specific? That being said the Security shield may have merit in the Pando set.

![image](https://user-images.githubusercontent.com/234593/218914777-0d5fd014-508b-4391-b0ea-388067149c59.png)

The mock (in Classic colours, don't ask!)
![image](https://user-images.githubusercontent.com/234593/218915044-06f59fb1-8230-47d8-beee-5418bf65e5c0.png)

The build in Pando, with `PlaceholderIcon` for the unsupported categories
![image](https://user-images.githubusercontent.com/234593/218915187-7d5f9df3-c8d2-48bd-8e3d-7dada47afb64.png)

### Expected behavior 🤔

Either the icons are included as part of Pando or ruled out, and will need to be moved to a Skills layer library.

### Steps to reproduce 🕹

N/A

**Comment by Rykus0** [comment]
@bradryanbice What do you think about adding these icons to Pando?

**Comment by bradryanbice** [comment]
@Rykus0 Sounds good to me, unless there is some limit or threshold we should be mindful of in the number of icons we include/support.

**Comment by bradryanbice** [comment]
@taitems Can you provide these assets that you need to include, please?

**Comment by taitems** [comment]
@bradryanbice I hadn't navigated to this section of the PSDS Icons file before but they're all listed down the bottom in a Skills specific icon section. 

![image](https://user-images.githubusercontent.com/234593/219981764-028d9ea5-ac85-4375-ab89-5c33913e6f44.png)

**Comment by Rykus0** [comment]
I did a little searching, and I think CAP was (is?) an acronym for Certified Analytics Professional.

@taitems Do you need all of these, or just some?  And are there others missing?  I see you have "Security" but it's using "cap-machine-learning", and the "Data & Machine Learning" heading is using "cap-iot".  I think it's good to avoid mixing metaphors, especially if these symbols change.  So maybe it would be better to identify which ones are missing, and how they're being used.  It may be that we are still adding the old icons, but under new names.  Especially if they're being used more broadly.

**Comment by taitems** [comment]
Hey Tom! In the following design the top-most `Data and Machine Learning` and `Security` icons from the original designer were not supported, and have been built out as PNGs. So in essence there is a workaround, but I wanted to flag the missing icons in case it crops up again, and for other designers.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/234593/222267692-fad6746f-a25f-443c-9f74-b35c0e8c6241.png">

**Comment by Rykus0** [comment]
For now, I'm going to add the "cap-iot" icon as "machine-learning" and "cap-machine-learning" as "security".  Any others that are needed we can add later.

**Comment by Rykus0** [comment]
What's funny is that the SVG exports were named this way, but the label in Figma was reversed. 🤷
