### ISSUE TITLE
[Feature?]: Admonition should support a Content Button

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1119]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The latest [Figma designs](https://www.figma.com/file/ZmH4XsZS5WnKeo28ylM5x1/Pando-UI-kit-(Web)?node-id=1214%3A50560&t=YLA3FBYLefNvfeuf-0) add a content button that is not styled like any of the buttons offered in Pando which means we need to add a custom style property.

Should also fit in a final breaking change before v1 and we are restricted from doing so converting the "wrapper" prop to use "container" to match the anatomy section.

Should probably just re-style the layout at this point to use a grid since it's getting a little wild with features.

### Motivation 🔦

Headlelss-styles, Admonition, Content Button

**Comment by Rykus0** [comment]
Note that in the cases where there is any interactive content, the `role` should be `alertdialog` instead of `alert`

**Comment by caseybaggz** [comment]
No longer relevant. After discussions with Design we agreed on creating a Toast component to handle this scenario.
