### ISSUE TITLE
[Feature?]: Avatar should support button usage

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1120]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The design rules allow the Avatar to have specific style rules if actionable. However, because the avatar is stylistically completely different than the Button, the the APIs semi-clash when combined.

![Screenshot 2023-02-27 at 9 45 10 AM](https://user-images.githubusercontent.com/4819738/221610551-ff887792-f7ce-4c86-baee-bba95f4d6c80.png)

### Examples 🌈

Avatar should return `buttonOptions` if `sentiment.action` is used which also may require more customization for the Button API to extend/merge classes or styles - whichever is more scalable.

### Motivation 🔦

Headless-styles, Avatar, Button, CSS

**Comment by Rykus0** [comment]
The Avatar already supports using a button element.  Do we need to support combining with the button API?

**Comment by caseybaggz** [comment]
> The Avatar already supports using a button element. Do we need to support combining with the button API?

Do you mind sending a link to the code that supports this? I'm not finding it and the solution posted above is proving that the API currently does not support it?

**Comment by Rykus0** [comment]
Yeah, definitely.  

The `wrapper` can be pretty much anything, but I made sure to specifically clear default button styles to allow for this. I think I had it in the documentation examples at one point, but can't remember why I changed it.  Probably to simplify.

I can fork a sandbox and send a link, too, if that helps.

```
export default function PlaceholderAvatar(props: AvatarOptions) {
  const { wrapper, iconOptions } = getAvatarProps(props)

  return (
    <button {...wrapper}>
      <PersonIcon {...getIconProps(iconOptions)} />
    </button>
  )
}
```

**Comment by caseybaggz** [comment]
> 

Yeah, using the wrapper like you have results in poorly styled UI when using a Button. Then, when you combine the APIs, you get weird states due to the shared Button styles/rules (photo in description). So ultimately, it does not support the use case in the snippet.
