### ISSUE TITLE
[Feature?]: Mutually exclusive options should either be unrepresentable or allow combinations

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/pando#1122]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, there are several components that essentially have mutually exclusive options, `sentiment` and `usage` for a button. As a user I would expect that if the types allow me to set both at once, e.g. 
```ts
type ButtonOptions = {
    sentiment?: ButtonSentiment
    usage?: ButtonUsage
}
```

then I should be able to pass both and know what to expect:

```ts 
const buttonProps = getButtonProps({ sentiment: 'danger', usage: 'outline' })
```

Currently, this results in what I would consider undefined behavior. You can't know for curtain without looking at the source code what style this will result in.

Looking at the documentation, it appears like you can _either_ specify the `sentiment`, and get a filled button with one of the named sentiment colors, _or_ you can specify the `usage` and choose to have an outlined or text button. If these options are mutually exclusive, I would argue that the type system should prevent you from using both, e.g.

```ts
export type ButtonOptions =
  | {
      sentiment: ButtonSentiment
      usage?: undefined
    }
  | {
      sentiment?: undefined
      usage: ButtonUsage
    }
```

Or, the implementation should accept any combination of `sentiment` and `usage` and output a valid, documented result.

### Examples 🌈

See this [typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQgrsYB7AdgZQi4BLAtp4KAXigHIBDAYx1VKgB8yATCAM3LgBtg7HSnyKAOYQATqQCwAKFCRYCZCgCqAZ3IjiZYBAAePBmVbZOnCE15kkCTthRnJU6dID0zqABUAFhBXQkYGhQVKEpBFCRCACNoIWwAN0wockJgbyg1fCgcfGlZaABZBDhyExAAUR1KTjgVeIh4RFQAeQDsVGCiaSgDAG8u7vSCPAIAfgAueUb0Ifwsfu6a9Qhxy2tbe36AX37GPqkBwaxhrBWKajaUBwPFkRWGxVUlradHKV0wJFEU8Gh75tb2sR+nsDq4PN5fFAwKJ-MFQigkpwAO7kEDBaLpSCUbBGMzzdLYABeywmpFwFlInCuUE2UAAZFBCsBiqUKlUanU-igWoEVC8WFVyKJoKw4ChzqgoCJgFyAAowsAqAAU-l5Ey5PIuKgAlBMxQBrcJIlAvaVyhXKnoE4mk8k07VQMFNfVQAC0UAAchBsKkxFBVRdMRBsbimKaIDKFKh5bClVbajayOSADRQG4QUnaPR0TYOp0u91NFCcED+uz+gEImp4qRmqMoGOKuPWjNJ0ip3xHWbAUkCYRiHN5tzOt1QIslst+Stp3xh151qaNy0t23tw7ZAikqiBNfpzO6fS5x3DgtQVQ+KAsdhcQidjdYKDSBeKJfNhOtslru-HHtkbcXXc1BEUkjBMex7WPMdT3PYIrw4bh1x-R95wjc1Y3jIkPxTRDu17Nh4J4VM91WYAbDscwIPzUcYMvfCbxnJ5a1Q+tXwwxNPw7GZN2YQQRHEIigI-KxSPWCijyo90aLg+j03DSNFwtN9MNXTiu24-g6O4QCln3bNKLcMpRBhURRwASRQOISmwJgQiQXBIiQJ9mIU9CVzbVT71-DTry0gSdMMYxTDEocoEM4yzIsqybMoOyHKc+SX0UtisK-LisF7XiBz84CtAPQdILCz4IssmxotixymIS6MkrcjicPUvs+O0nLSFAoL8rBQqTPdcySus2z7IqoA) for an example of resulting the end-user experience.

### Motivation 🔦

The goal should be to [make impossible states unrepresentable](https://kentcdodds.com/blog/make-impossible-states-impossible) ([another blog post about the same topic in F#](https://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable/#why-bother-to-make-these-complicated-types)). This will help towards the goal of making it _"easy to do things the 'right' way, and hard/annoying to do things the 'wrong' way"_.

Personally, I would argue that it would be easier and simpler on several fronts to just allow for the `sentiment` to essentially act as the color and the `usage` act as the variant, with one more variant added (e.g. `default` or `filled` in this case to represent what currently happens without specifying a `usage`), and allow them to be mixed and matched arbitrarily. But, if allowing this goes against what the new branding wants to allow, then I think we should strive to make it clear by the types what combinations are actually allowed.

**Comment by caseybaggz** [comment]
@josh-degraw great topic of conversation and one that creates the foundation of why we made this API the way we did - to scale and also directly connect to our Themes/semantic-token naming convention. I ultimately agree with you on the overall concept though. 

Right now, design is restricting us from the API being fully compound, but do we just build it that way and only promote the "allowed" cases? Good question for the API indeed.

**Comment by josh-degraw** [comment]
Another alternative could be replacing `sentiment` and `usage` in this case for one combined prop e.g. `variant` which would accept either a sentiment or a usage. That way it would still be restricted to only the allowable variations without having to rely on any complex type-level stuff, and would make invalid states truly unrepresentable.

e.g. 
```ts
type ButtonSentiment = 'default' | 'danger' | 'action'
type ButtonUsage = 'text' | 'outline'
type ButtonVariant = ButtonSentiment | ButtonUsage

type ButtonOptions = {
   variant?: ButtonVariant 
}
```

The main problem with this approach, other than breaking change (although it certainly could be done in a backwards compatible way), is that it would make it harder in the future to support mixing sentiment with usage if that is something that might end up happening. But I wanted to bring up the option at least haha.

**Comment by caseybaggz** [comment]
> Another alternative could be replacing `sentiment` and `usage` in this case for one combined prop e.g. `variant` which would accept either a sentiment or a usage. That way it would still be restricted to only the allowable variations without having to rely on any complex type-level stuff, and would make invalid states truly unrepresentable.
> 
> e.g.
> 
> ```ts
> type ButtonSentiment = 'default' | 'danger' | 'action'
> type ButtonUsage = 'text' | 'outline'
> type ButtonVariant = ButtonSentiment | ButtonUsage
> 
> type ButtonOptions = {
>    variant?: ButtonVariant 
> }
> ```
> 
> The main problem with this approach, other than breaking change (although it certainly could be done in a backwards compatible way), is that it would make it harder in the future to support mixing sentiment with usage if that is something that might end up happening. But I wanted to bring up the option at least haha.

Yeah we definitely don't want to go that route because it's just not scalable. That's where we started and it just didn't scale or compliment the ecosystem like what we are doing now. 

But also...major breaking change and worse, elminates the consistency of sharing the same design of semantic naming.

**Comment by Rykus0** [comment]
Thanks @josh-degraw, I also noted this before but hadn't created an issue for it yet.  I made a small adjustment to the CSS recently that helps, but doesn't completely solve.  We definitely want to keep the two options, so we have to decide in which way they should function that is in line with the design intent
