### ISSUE TITLE
[Bug?]: Table styled incorrectly

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1124]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Current Table is styled by the wrong Figma file.

### Expected behavior 🤔

Styles should reflect the "overview" Table, not the "status" section.

### Steps to reproduce 🕹

n/a

### Context 🔦

Headless-styles, Table, CSS

**Comment by Rykus0** [comment]
@caseybaggz Should this also include the scroll styles (I can check with brad on details) and row-density options?  Or just the basic appearance? (I have the basic styles done)

**Comment by caseybaggz** [comment]
I don't think we have scroll specific styles? More than welcome to validate with Brad though.
