### ISSUE TITLE
[Feature?]: Adding Figma icon(s)

### ISSUE THREAD

**Issue by bradryanbice** [pluralsight/pando#1126]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Adding Figma icons in SVG format.

![figma-color](https://user-images.githubusercontent.com/8323556/221923962-0f8c3cb1-88a8-4b17-a193-b4bae8b849a6.svg)
![figma-outline](https://user-images.githubusercontent.com/8323556/221923967-6b6d46db-62c8-4b98-9868-3a2aabe95e9b.svg)

### Examples 🌈

<img width="282" alt="CleanShot 2023-02-28 at 11 58 29@2x" src="https://user-images.githubusercontent.com/8323556/221923746-52ed2245-2579-4a11-8bf4-a8b38101ef54.png">

Adding outline and color versions. One-color (all-black or all-white) doesn't work so well with this particular mark.

**Comment by Rykus0** [comment]
@bradryanbice we can't support the full-color icon right now. We've assumed simple, single-color icons controlled by the current `color`.  I can look into what we'd need to support them, maybe in our whiteboarding.  How important is it to have the full-color icon?

**Comment by bradryanbice** [comment]
> @bradryanbice How important is it to have the full-color icon?

Not important. I included it to be complete, and because I'm not a huge fan of the outline version, but really whatever works best with our system now is A-OK.

**Comment by Rykus0** [comment]
Closing this since the single-color icon has been added.  If we need to add full-/multi-color icons later, we can address that separately.
