### ISSUE TITLE
[Bug?]: Jest tests failing because of undefined styles module

### ISSUE THREAD

**Issue by GianaS** [pluralsight/pando#1127]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Jest tests are failing because of `undefined` styles from css modules.  The styles are correctly defined in our local environment and in Storybook.  We believe this error is because the `styles` module is generated on build (according to [this file's comments](https://github.com/pluralsight/pando/blob/1929abaaf7b6b7f051574705c871e8b828736a4e/packages/headless-styles/src/components/Icon/generated/iconCSS.module.ts)) and the module is not generated during tests; hence the `undefined` styles module.  The only issue is during Jest tests.  The examples I'm showing here are from the Icon, but it's happening for other components as well.

This issue does not happen to versions prior to 0.4.x.

We were able to reproduce this issue by putting the Pando unit tests in our local environment.  We copied the tests in [this Pando test file](https://github.com/pluralsight/pando/blob/8190ce720dc005b4020c9c854f5229c506bef25b/packages/headless-styles/tests/icon/iconCSS.test.ts) in our repo to produce the same failure as our own tests.  We could not get the tests to run directly in the Pando environment, but would appreciate it if someone who has Pando running locally can confirm that the tests are failing directly in Pando as well.

![test failure](https://user-images.githubusercontent.com/40693732/221922428-113c405f-54df-4bb3-8d5e-d825a24bad86.jpg)

### Expected behavior 🤔

We expect either:

1. the tests to correctly pass as they did in Pando versions prior to 0.4.x
2. guidance on how to proceed (mocks, something else, etc) depending on how y'all resolve the tests on your end

### Steps to reproduce 🕹

Steps:

1. Run the tests in the Pando repo
2. Should see the same failure as screenshotted above

### Context 🔦

This issue is blocking us from progressing in our rebranding work because our tests are not passing.

**Comment by caseybaggz** [comment]
@GianaS hello! All of our tests are passing which you can validate on any branch via the CI status on the repo. Likewise, in Jest you have to exclude CSS since it doesn't handle that file use case which looks to me like what you are missing in your local repo.

You can just copy our [test configuration](https://github.com/pluralsight/pando/blob/main/jest.config.js#L12-L20) which should solve the problem.

**Comment by GianaS** [comment]
Oh thanks for pointing us to your jest config.  Looks like we just had to generalize our `moduleNameMapper` regex to capture the css modules.  We are up & running again.  Thank you!
