### ISSUE TITLE
[Feature?]: Prompt API

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1132]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Our Modal rules reference a Prompt Dialog which we neither have designs or an API for, but should to match the browser API for dialogs specifically for collecting form field like data.

### Examples 🌈

Design Standard: Do not use Modals for prompting the user to input data, use Prompt Dialog for this.

### Motivation 🔦

Headless-styles, Dialog, Prompt

**Comment by bradryanbice** [comment]
This is now in the UI-Kit, but not referenced in the Overview yet (and not advertised elsewhere): https://www.figma.com/file/ZmH4XsZS5WnKeo28ylM5x1/Pando-UI-kit-(Web)?node-id=7110%3A69131
