### ISSUE TITLE
[Bug?]: Headless-styles doesn't work for Next13

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1146]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The new NextJS version using the "app" directory switches to use Sever Components - a new feature React concurrent mode ships with. Unfortunately, because we are code-splitting the styles into CSS-in-JS and not creating CSS module chunks, Headless styles will not style anything in a Sever Component.

This means that in order for HS to work within the latest NextJS, the user has to "opt-out" of server components and use client side which defeats the purpose of using NextJS.

[You can see an example here](https://github.com/caseybaggz/website/blob/main/components/Nav/index.tsx)

Via Next Beta Docs:
> If you want to style Server Components, we recommend using [CSS Modules](https://beta.nextjs.org/docs/styling/css-modules) or other solutions that output CSS files, like PostCSS or [Tailwind CSS](https://beta.nextjs.org/docs/styling/tailwind-css).

### Expected behavior 🤔

Headless-styles should be compatible for both Server and Client components.

### Steps to reproduce 🕹

Steps:

1. Create a new NextJS repo using the **new appDirectory feature**
2. Install HS
3. Add a new button with the `getButtonProps` API on the `page.tsx` file
4. **See all the attributes and no styles**
5. Add `'use client'` at the top of the page
6. **See the styles are added due to using CSS-in-JS in the production build**

### Context 🔦

Headless-styles, Rollup, tree-shaking

**Comment by caseybaggz** [comment]
Doing more research makes it hard to believe a proper UI component library can live on the server ([see chart](https://beta.nextjs.org/docs/rendering/server-and-client-components)), so I'm going to experiment a little more in my personal project then probably just add a page to the docs about how to use with Next 13.

**Comment by caseybaggz** [comment]
Here is an example of [installing Tailwind into Next 13](https://beta.nextjs.org/docs/styling/tailwind-css).

**Comment by caseybaggz** [comment]
Found out you can use Pando with Server Components via the JS APIs. I don't love it, but it works. We might need to have "Server components" and "Client" listed on the docs site when we build the components lib.

**Comment by ThatJoeMoore** [comment]
Hey, I keep meaning to chime in here, but I've been crazy busy. Integration work, you know?

Here's what I see as the alternatives:

1) Current, injected-by-JS stylesheets
2) Standard CSS Module imports ([`import foo from './foo.css' assert {type: 'css'}`](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md))
3) Non-standard, Webpack-style imports (`import from './foo.css'`)

1) has performance issues, requires JS to be enabled, and apparently doesn't work with (React Server Components). However, it doesn't require any special build/framework configuration.
2) Is still a proposal (though it's very very likely to ship in its current form), doesn't have any real support in frameworks/builders yet, but would theoretically work without any special support (though it's unknown if it will work with RSC)
3) Is non-standard and requires build tool support but, for the most part, frameworks/builders either work properly with it or don't need much config to do so.

As much as it pains me to ship something that requires builders, it seems like the optimal path for everyone will be to support #3 somehow.

One thought I had is to leverage [Conditional Exports](https://nodejs.org/docs/latest-v16.x/api/packages.html#conditional-exports) to produce two build artifacts, representing #1 and #3. Once CSS modules gets to a more usable state, we could add that to an export.

The big decision with this would be which thing to make the 'default' export. Part of me thinks the current solution should be the default, as it's a little more universal in how it works, but the #3 solution is going to be the correct choice more often. Besides, for anything in package.json to make a difference, you'd have to be using some form of build tooling, which means that you should be able to specify which conditional export to use.

My current thinking would be to make the #3, Next/Remix/Etc. friendly approach the default export, and come up with a different name for the 'builder-less' version.  We could then provide instructions for common tools/frameworks for using the correct conditional export:

* [Webpack](https://webpack.js.org/configuration/resolve/#resolveconditionnames)
* [Rollup + plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve#exportconditions)
* [esbuild](https://esbuild.github.io/api/#conditions)
* [Vite](https://vitejs.dev/config/shared-options.html#resolve-conditions)
