### ISSUE TITLE
[Feature?]: Allow Button to compose with Avatar

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/pando#1295]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Using an Avatar inside a Button should work without any additional effort.  Right now, button styles (height, mainly) interfere with the expected result of combining these two.

One way of achieving this could be using the CSS `:has` selector - for example:
```css
.button:has(.pando-avatar) {
  /* reset any interfering styles */
}
```

### Examples 🌈

```html
<Button usage="text">
   <Avatar sentiment="action" />
</Button>
```

**Comment by caseybaggz** [comment]
closed with #1293
