### ISSUE TITLE
[Bug?]: Icons lib not allowing props

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1401]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using any Icon from the `@ps/icons` library, the templates that are created are overly strict and do not allow the user to pass any props to the icons. This is causing the React library to have bugs due to HS or React to not be able to pass any properties to overwrite the component.

For example, this:
```jsx
<Icon
        ariaHidden={false}
        ariaLabel="test"
        customSize="100%"
        icon={PlaceholderIcon}
      />
```

Is producing this result due to it's unnecessary control and of flexibility:
```html
<svg
            aria-hidden="true"
            aria-label="placeholder icon"
            class="pando-icon pando_mIconSize"
            fill="currentColor"
            role="img"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
```

### Expected behavior 🤔

The above example should instead result in this outcome:
```diff
<svg
+            aria-hidden="false"
+           aria-label="test"
            class="pando-icon pando_mIconSize"
            fill="currentColor"
            role="img"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
```

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

Icons, React

**Comment by josh-degraw** [comment]
Are the `aria` props in the lib expected to be `camelCase`? If so I would argue standardizing around `kebab-case` since that's how they're handled on builtin elements, to keep things consistent with the larger ecosystem
