### ISSUE TITLE
[Bug?]: result box for components is broken for several pages on the 0.4.1 documentation

### ISSUE THREAD

**Issue by pawlh** [pluralsight/pando#1544]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For the latest stable version, 0.4.1, the result boxes on some component pages show error messages instead of a demo of the component.

Error messages include:
"TypeError: Cannot read properties of undefined (reading 'value’)”
"TypeError: Cannot read properties of undefined (reading 'className’)”
“ReferenceError: getFormControlProps is not defined”

### Expected behavior 🤔

For each component, there should be a functioning demo accompanying code examples in the Live Editors

### Steps to reproduce 🕹

Steps:

1. Navigate to a broken component's docs (see list below)
3. Scroll down to a section that has Result and Live Editor boxes
   - e.g. https://design.pluralsight.com/docs/reference/components/avatar#static-avatar
5. Note that instead of a component being rendered, an error message is shown

Affected URLs: 
- https://design.pluralsight.com/docs/reference/components/avatar
- https://design.pluralsight.com/docs/reference/components/checkbox
- https://design.pluralsight.com/docs/reference/components/field-message
- https://design.pluralsight.com/docs/reference/components/form-control
- https://design.pluralsight.com/docs/reference/components/form-label
- https://design.pluralsight.com/docs/reference/components/input
- https://design.pluralsight.com/docs/reference/components/radio
- https://design.pluralsight.com/docs/reference/components/select
- https://design.pluralsight.com/docs/reference/components/switch
- https://design.pluralsight.com/docs/reference/components/text-area

### Context 🔦

The applications I work on use version 0.4.1, so when I am looking over the docs I frequently see these errors instead of more helpful examples.

**Comment by caseybaggz** [comment]
@pawlh this is not a bug. Unfortunately our docs can only source one version of a project and right now we are weeks away from releasing v1 so until then, the "latest" docs will be broken.

Instead, please use the "next" version for all your needs. 👍
