### ISSUE TITLE
[Feature?]: Update heading-5 line-height

### ISSUE THREAD

**Issue by bradryanbice** [pluralsight/pando#1607]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

`line-height` for heading level 5 style should be increased from `1.25` to `1.5`

### Motivation 🔦

It looks better.

**Comment by jaykesarkar** [comment]
I would like to work on this issue. Please guide me.

**Comment by caseybaggz** [comment]
> I would like to work on this issue. Please guide me.

Check out our README's in each package for context. We manage h styling in the tokens package and this would be the normalize file. 👍
