### ISSUE TITLE
[Feature?]: pando cli setup: install dependencies

### ISSUE THREAD

**Issue by kathydlavoie-ps** [pluralsight/pando#1754]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- [x] running `pnpx pando setup` should
  - [x] detect & confirm PM pref (bun, npm, yarn, pnpm)
  - [x] install `@pluralsight/{react,icons}`
  - [x] install `@pluralsight/panda-preset`
  - [x] install `@pandacss/dev`
  - [x] install `postcss` (if not already installed)
  - [x] install `autoprefixer` (if not already installed)

**Comment by caseybaggz** [comment]
Pivoting to preset. Closing.
