### ISSUE TITLE
[Feature?]: convert prepare/publish scripts

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1776]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- [ ] Add Bun scripts
- [ ] Update package.json
- [ ] Update GH Actions

**Comment by kathydlavoie-ps** [comment]
after #1777 was merged the build began passing, fixing this bug. This exposed another bug #1779. Closing this issue.
