### ISSUE TITLE
[Feature?]: Add icons to the code Icon library

### ISSUE THREAD

**Issue by KtlPro** [pluralsight/pando#1805]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello! Per our [conversation in slack](https://pluralsight.slack.com/archives/C03D8G0V42G/p1697561556387509), there are some icons that haven't, yet, been added to the Pando library of icons.

### Examples 🌈

These text editing icons found [here](https://www.figma.com/file/zAHNqE6nbctn26wGADu2vo/Pando---Icons?type=design&node-id=20-307&mode=design&t=Yo9h8tgSRrJhXx3G-0).

There is also this `list-checks` component that looks like [this](https://www.figma.com/file/ajvL7ehUXfftbl4VIFIqO3/ILX-Course-Builder?node-id=1414%3A390611&mode=dev) (hopefully that links correctly).

Let me know what else is needed on my part.

### Motivation 🔦

I am building how a WYSIWYG/Markdown Rich text editor for the Course Builder BC and found these icons in Merilee Benson's designs, but not in the `@pluralsight/icons` package (there were only 2 or so).

**Comment by bradryanbice** [comment]
[text edit icons.zip](https://github.com/pluralsight/pando/files/12952398/text.edit.icons.zip)

Here are the exported SVG files.
