### ISSUE TITLE
[Docs?]: relocate the website workspace

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1941]
### Latest version

- [X] I have checked the latest version

### Summary 💡

Relocate the `website` workspace and all the settings, configs, etc. to the new repo:
https://github.com/pluralsight/pando-beta-docs

Probably should use pnPm since Bun isn't too reliable yet.

**Comment by kathydlavoie-ps** [comment]
closed by https://github.com/pluralsight/pando/pull/1995 & https://github.com/pluralsight/pando-beta-docs/pull/4
