### ISSUE TITLE
[Feature?]: (docs) migrate typography from figma ui kit

### ISSUE THREAD

**Issue by kathydlavoie-ps** [pluralsight/pando#1965]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Migrate [figma ui kit font reference](https://www.figma.com/proto/uJtPfI38D9i8iQg0UGK2E0/Pando-Design-Guidelines?page-id=0%3A1&type=design&node-id=533-15987&viewport=1226%2C-14299%2C0.55&t=M7BKfoKdz6EBQ7ax-1&scaling=min-zoom&starting-point-node-id=6%3A11626) to reference section of new docs

### Motivation 🔦

To provide reference material for users exploring the typography used in the pando design system

**Comment by caseybaggz** [comment]
@kathydlavoie-ps this should reference and promote the `testStyles` API from the preset which is based on the Figma Typography
