### ISSUE TITLE
[Feature?]: add class merge in HS

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#868]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, HS doesn't offer any `class` utilities which forces the user to do custom logic to combine class styles  which can be tedious in certain scenarios (i.e. user also uses CSS Modules in combination with HS CSS modules). It would be nice to be able to just extend the classes to allow the native CSS API to be more fluid.

### Examples 🌈

```javascript
const oneColItem = getGridItemProps({ colSpan: 1, class: styles.container })
```

results in:
```typescript
interface GridItemProps {
  className: 'ps-grid-item user_cssModule_class ps_gen_cssModule'
  style: ...
}
```

**Comment by Rykus0** [comment]
This gets complicated for components with multiple elements - which element should the classes go on?

We could export a helper to merge classes with a specific set of returned props, but that could get awkward.  

For now, I will add this only to the helpers which apply to a single element.  For those with multiple, I will apply the classes to the outer-most element.

**Comment by Rykus0** [comment]
I was thinking about refactoring `createClassNameProp` to accept an array instead of the two strings.  That would allow us to skip any undefined classes and I feel is easier to work with and read. 

Usage would look something like this:

```
function getComponentProps(options) {
	 return {
		 ...createClassNameProp([
			'ps-switch-container',
			styles.container,
			styles[sentimentClass],
			defaultOptions.className,
		 ])
	 }
}
```

**Comment by Rykus0** [comment]
For multi-element components, we could accept an object whose keys align with the helper's output and assign the classnames that way. 

```
getComponentProps({
	className: {
		 wrapper: 'class-name',
		 element: 'element-class',
	}
})
```

**Comment by caseybaggz** [comment]
Going to close this since we are not doing it any time soon.
