### ISSUE TITLE
[Feature?]: add useTheme hook

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#879]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

There is currently no helper for teams that are responsible for theming. We should provide a custom hook that sources and caches the theme from localStorage for teams to use.

#### Overall architecture

package: react-utils

Store and source theme from localStorage with `ps-theme` key.

- [ ] Should accept a parameter for initial value
- [ ] Should retrieve initial localStorage value (outside of hook)
- [ ] Should use localStorage value for initial value if no param given
- [ ] Should store updated value in localStorage
- [ ] Should include unit tests via component usage strategy (see other hook tests)

### Examples 🌈

Something to the effect of [this example](https://github.com/pluralsight/tva/blob/main/packages/headless-styles/sandbox/src/App.jsx#L9-L26), or whatever may be better performance wise.

**Comment by nicholasmackey** [comment]
I'd like to help with this one. Is this something I can take on and work on? Let me know if there's anything specific I can do to assist. Thanks! ✌️

**Comment by caseybaggz** [comment]
@nicholasmackey absolutely! Let me create a better description for you. 👍

**Comment by nicholasmackey** [comment]
Hey @caseybaggz - thanks for updating the description!

I just had a quick question about the hook's functionality. Would you like it to only support a dark or light theme option, or should it be able to handle an infinite number of themes? 

Something like [GitHub's theme switcher](https://github.com/settings/appearance). 

Could you please let me know your thoughts on this?

**Comment by caseybaggz** [comment]
Great question! Let's start with just "light" and "dark". Then once it's shipped, we can see about adding features to it.

**Comment by nicholasmackey** [comment]
Perfect. Thanks for responding so quickly. ✌️

**Comment by nicholasmackey** [comment]
Hey @caseybaggz - I had one more question for you. I noticed that in the [documentation](https://design.pluralsight.com/docs/development/tokens/colors/#themes), themes are controlled by using an attribute on the html tag (data-theme) similar to the [example](https://github.com/pluralsight/tva/blob/main/packages/headless-styles/sandbox/src/App.jsx#L24) you provided.

Would you also like me to include setting the attribute with the `ps-theme` key with the hook?

**Comment by caseybaggz** [comment]
@nicholasmackey Great question and yes!
