### ISSUE TITLE
[Bug?]: TS Types for some returned attributes are incorrect

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/pando#901]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For attributes that have a defined subset of values, we are getting TS errors when assigning the returned props directly.  
This is primarily aria-* attributes

### getErrorMessageProps
**aria-live**: Type 'string' is not assignable to type '"off" | "assertive" | "polite" | undefined'.

### getPopoverProps
**aria-haspopup**: Type 'string' is not assignable to type 'boolean | "dialog" | "menu" | "true" | "false" | "listbox" | "tree" | "grid" | undefined'.

### getSwitchProps
**aria-hidden**: Type 'string' is not assignable to type 'Booleanish | undefined'.

### Expected behavior 🤔

Spread returned props on the target element without type errors.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by Rykus0** [comment]
Looks like this is specific to React types, not Typescript in general (which defines them as `string | null`.
See `@types/react/index.d.ts` > `AriaAttributes`

**Comment by caseybaggz** [comment]
@Rykus0 you could submit a PR to the package in this repo:
https://www.npmjs.com/package/@types/react

**Comment by caseybaggz** [comment]
relates to #1169
