### ISSUE TITLE
[Feature?]: Align Switch font styles

### ISSUE THREAD

**Issue by bradryanbice** [pluralsight/pando#951]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Switch label styles should be updated to match Figma design specs:

A slightly larger gap between label and control - 14px/1em

### Examples 🌈

Current example from docs:
<img width="279" alt="CleanShot 2023-01-05 at 10 48 40@2x" src="https://user-images.githubusercontent.com/8323556/210841104-0fc65411-9f6c-471e-8d47-2e2354b3a182.png">

Figma example:
<img width="327" alt="test" src="https://user-images.githubusercontent.com/8323556/211057047-5d3c68a7-a47a-4c70-9a27-d603054f30a4.png">

### Motivation 🔦

We are also allowing an icon in the Figma component (such as `info-circle`), but that may be for another issue.

**Comment by Rykus0** [comment]
@bradryanbice - if the font size is 14px, would the same size work for the gap?  (1em)

Also, does the same apply for radio and checkbox?  Currently we're using the same label styles for all form elements.  I'm assuming for controls like these, that would be the group label, and the individual control would use the label you're describing in this issue.

**Comment by caseybaggz** [comment]
@bradryanbice right now we are using FormLabel for all input related labels vs. making them independent for specific components (i.e. Switch uses the same form label styles as Input).

**Comment by bradryanbice** [comment]
@Rykus0 I tried the 14px gap size, and it just seemed a bit off. I know 0.8 and 12px are funny values, and if we're trying to shore that up a bit, I'm happy just to go with 14px/1em.

I haven't necessarily tested this out with Radio and Checkbox just yet, but in theory, yes. But that is something I want to test out. eg. with the same size group and Individual labels, do things get more or less confusing in visual hierarchy on a busy form.

@caseybaggz I'm checking with a few people on if we should make Switch labels bold. Many times these are longer and wouldn't be, so I'm checking the direction there.

**Comment by bradryanbice** [comment]
@caseybaggz @Rykus0 Updated the original issue comment. So, effectively just doubling the gap between the label and control. And now the Figma example is using the same label styles as Form Control and Radio/Checkbox groups.

**Comment by Rykus0** [comment]
@caseybaggz @bradryanbice I'm considering the icon as within the label.  So the label will be 14px from the switch, and icons within labels will be 12px offset from the text.  Let me know if there are any issues with that approach.

**Comment by bradryanbice** [comment]
@Rykus0 That sounds good to me.

**Comment by caseybaggz** [comment]
> @caseybaggz @bradryanbice I'm considering the icon as within the label. So the label will be 14px from the switch, and icons within labels will be 12px offset from the text. Let me know if there are any issues with that approach.

I'm not sure this is an API problem. Adding an icon to a label by nature is just combining the two API's for this specific use case so we technically don't need to do anything in our APIs. So, the only thing that needs to change IMO, is the spacing around the switch to support a label being combined with it.

**Comment by Rykus0** [comment]
The spacing is already around the switch - that's easy. We only need to update the value there.

The icon is something we haven't accounted for yet, and still needs to be sized and spaced.  If we're combining it with the Label, we can return `iconOptions` like we do elsewhere to account for labeling, sizing, and other styles. But the label still needs to handle the spacing - exactly like how the switch handles the spacing between the control and the label.
