### ISSUE TITLE
[Feature?]: Remove input, select, textarea background-color

### ISSUE THREAD

**Issue by bradryanbice** [pluralsight/pando#957]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Input, select, and textarea elements should no longer have a background color, but would rather have a transparent background.

### Examples 🌈

Current docs example:
<img width="998" alt="CleanShot 2023-01-06 at 12 01 45@2x" src="https://user-images.githubusercontent.com/8323556/211060900-0811fe3e-e9e5-44f2-a578-0c554246bb01.png">

Desired as seen in Figma:
<img width="901" alt="Regression testing" src="https://user-images.githubusercontent.com/8323556/211060934-4ebd2bc5-8ff5-41c0-9a0f-c6ffb232aab7.png">

### Motivation 🔦

Form containers will likely get a standard background to differentiate them. This change allows form elements to work on a variety of backgrounds without strange combinations of surface colors compounding and over-saturating experiences.

**Comment by caseybaggz** [comment]
@bradryanbice it's typically considered a bad engineering practice to use transparent background colors for inputs since it opens the doors pretty wide to potential UI bugs depending on the layout (which we can't control every single scenario).

Would we be able to instead use the same background color you plan on using for the form containers specifically for users who need to use inputs outside of forms (i.e. search, etc.)?

**Comment by bradryanbice** [comment]
@caseybaggz The problem is we don't know where these inputs will be used, and often get used in multiple different spots that may or may not take on the same universal form background (if that becomes a thing). If we were able to access something like `currentColor` except for backgrounds, then sure.

**Comment by caseybaggz** [comment]
> @caseybaggz The problem is we don't know where these inputs will be used, and often get used in multiple different spots that may or may not take on the same universal form background (if that becomes a thing). If we were able to access something like `currentColor` except for backgrounds, then sure.

We can totally use current color! That would definitely help.
