### ISSUE TITLE
[Feature?]: Align Checkbox/Radio styles

### ISSUE THREAD

**Issue by bradryanbice** [pluralsight/pando#968]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently styles for Checkbox and Radio are misaligned between Figma and the codebase:

- Target boxes should use 2px border-width
- border-color should be action/border
- Label should use normal font-weight and 16px (1em) font-size
- Layout example should show checkboxes and radios stacked instead of inline

### Examples 🌈

Current headless styles example:
<img width="452" alt="CleanShot 2023-01-10 at 11 23 06@2x" src="https://user-images.githubusercontent.com/8323556/211606917-4a905642-a2cb-4755-8220-cea3c6ef28ac.png">

Figma example:
<img width="299" alt="checkbox" src="https://user-images.githubusercontent.com/8323556/211606949-adff9bca-8eec-447c-a038-f48c39255137.png">

### Motivation 🔦

- Stroke width was recently updated (2023-01-10)
- Potentially an issue using the form label, however I don't see where we'd want the smaller, bold labels on checkboxes and radios.

**Comment by caseybaggz** [comment]
@bradryanbice just a note that this change will inherently ship the same styles to the Input since all labels are the same (like the HTML element).

**Comment by bradryanbice** [comment]
@caseybaggz Gah, this is severely limiting and I don't like it. Let's leave the font styles as-is, then. And I guess we'll see if there are complaints about small, chunky labels that match the top-level label styles.

**Comment by caseybaggz** [comment]
@bradryanbice I hear you, but to change it unnecessarily complicates the engineering, which is why we are trying to create a model based on consistency vs. uniqueness on each element (i.e. all inputs are consistent vs. individual inputs like radio/checkboxes).

I'll update my PR to remove the font updates.
